project:
  type: website
  output-dir: docs

website:
  title: "Quantitative Geographie: Mobile Gesellschaft"
  navbar:
    left:
      - href: index.qmd
        text: Intro
      - 01_basics.qmd
      
format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true



